StartupEvents.registry("item",event =>{
    event.create("sausage","basic").food(food=>{
        food.hunger(3)
        food.saturation(2.0)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("cooked_sausage","basic").food(food=>{
        food.hunger(8)
        food.saturation(2.0)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("oxtail","basic").food(food=>{
        food.hunger(2)
        food.saturation(1.0)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("liver","basic").food(food=>{
        food.hunger(3)
        food.saturation(1.0)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("heart","basic").food(food=>{
        food.hunger(2)
        food.saturation(1.2)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("brain","basic").food(food=>{
        food.hunger(3)
        food.saturation(1.2)
        food.fastToEat(true)
        food.meat(true)
    })
    event.create("ribs","basic").food(food=>{
        food.hunger(5)
        food.saturation(1.2)
        food.fastToEat(true)
        food.meat(true)
    })
})