ItemEvents.tooltip(event => {
    event.add("thermal:ruby_ore","由镭射钻挖掘，不会自然生成")
    event.add("thermal:deepslate_ruby_ore","由镭射钻挖掘，不会自然生成")
    event.add("kubejs:wireless_connect_broken",Text.yellow("在天境的小行星实验室被发现"))
    event.add("ae2additions:me_wireless_transceiver",Text.yellow("这个设备存在崩档bug，故已被禁用。如果你清楚崩溃触发条件并且很想用这个，请自行作弊获取，且不要将崩溃反馈给制作组"))
    event.add("kubejs:steel_leaved_iron_block",Text.aqua("随时间风化（可被晶体催生器加速）"))
    event.add('pneumaticcraft:security_upgrade',Text.red("合成已被禁用，可在天境的小行星实验室中少量发现"))
    event.add("pneumaticcraft:safety_tube_module",Text.red("合成已被禁用，可在天境的小行星实验室中少量发现"))
    event.add("tinkerscalibration:iceland_spar_crystal","发现于霜原星深层地下")
    event.add("tinkers_thinking:chlorophyll_ore","常见于丛林浅层地下")
})